from dataclasses import dataclass
from pydantic import BaseModel, Field
from datetime import datetime
from firebase_admin import firestore

class ChatRequest(BaseModel):
    """The request model for a new chat message from the client."""
    user_message: str = Field(..., min_length=1, description="The text content of the user's message.")
    message_id: str = Field(..., min_length=1, description="A unique ID for the message, generated by the client (e.g., a UUID).")
    client_timestamp: datetime = Field(..., description="The UTC timestamp when the message was sent, generated by the client.")

class ChatResponse(BaseModel):
    """The response model confirming the request was processed."""
    status: str = "success"
    message: str = "Request received and is being processed."

@dataclass
class AgentContext:
    """A structured, type-safe context object for an agent run."""
    user_id: str
    user_timezone: str
    firestore_batch: firestore.WriteBatch