from dataclasses import dataclass
from typing import Literal
from pydantic import BaseModel, Field
from datetime import datetime
from firebase_admin import firestore

class ChatRequest(BaseModel):
    """The request model for a new chat message from the client."""
    user_message: str = Field(..., min_length=1, description="The text content of the user's message.")
    message_id: str = Field(..., min_length=1, description="A unique ID for the message, generated by the client (e.g., a UUID).")
    client_timestamp: datetime = Field(..., description="The UTC timestamp when the message was sent, generated by the client.")

class ChatResponse(BaseModel):
    """The response model confirming the request was processed."""
    status: str = "success"
    message: str = "Request received and is being processed."

@dataclass
class AgentContext:
    """A structured, type-safe context object for an agent run."""
    user_id: str
    user_timezone: str
    firestore_batch: firestore.WriteBatch

class ScheduledNotification(BaseModel):
    """Data model for a document in the 'scheduled_notifications' collection."""
    user_id: str = Field(alias="userId") # Use alias to map to Firestore's camelCase
    title: str
    body: str
    scheduled_at: datetime = Field(alias="scheduledAt")
    status: Literal["pending", "sent", "failed"]
    created_at: datetime = Field(alias="createdAt")
    user_timezone: str = Field(alias="userTimezone")
    
    class Config:
        # Allow population by alias to make instantiation in Python code cleaner
        populate_by_name = True